//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Appointments')
export class AppointmentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  healthcareProviderName: string;

  @Column('date', { nullable: true })
  appointmentDateAndTime: Date;

  @Column('text', { nullable: true })
  purpose: string;

  @Column('text', { nullable: true })
  specialInstructions: string;
}
