//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('BloodTestResults')
export class BloodTestResultsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('date', { nullable: true })
  testDate: Date;

  @Column('text', { nullable: true })
  testType: string;

  @Column('text', { nullable: true })
  results: string;

  @Column('text', { nullable: true })
  interpretation: string;

  @Column('text', { nullable: true })
  recommendations: string;
}
