//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('EducationalResources')
export class EducationalResourcesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  content: string;

  @Column('date', { nullable: true })
  publicationDate: Date;

  @Column('text', { nullable: true })
  authorOrSource: string;
}
