//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Medications')
export class MedicationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  medicationName: string;

  @Column('text', { nullable: true })
  dosage: string;

  @Column('text', { nullable: true })
  frequency: string;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('date', { nullable: true })
  endDate: Date;

  @Column('text', { nullable: true })
  specialInstructions: string;
}
