//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="THE BLOOD CARE" />
    <CardContent>
      A blood care app that includes interfaces for user registration,
      dashboard, blood test results, appointment scheduling, medication
      reminders, blood donation, educational resources, community forum,
      emergency interface, and hospital details.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
